const rooms=[["😂","Just Chatting",1284,"Social"],["🎵","Music",976,"Lifestyle"],["🎮","Gaming",603,"Lifestyle"],["⚽","Football",557,"Lifestyle"],["💼","Jobs & Careers",842,"Career"],["💻","Tech",391,"Career"],["💰","Side Hustles",419,"Career"],["🎓","Students",734,"Career"],["🌍","General",1120,"Social"],["🌊","Durban",688,"Places"],["🏙️","Johannesburg",1056,"Places"],["⛰️","Cape Town",901,"Places"],["🌳","Pretoria",512,"Places"],["🌅","Gqeberha",247,"Places"],["🌻","Bloemfontein",198,"Places"]]; let activeCat="All";
const people=["Zee","Thando","Lebo","Kay","Amahle","Neo","Sbu","Mia"]; const userData={Zee:["Durban","Music, Football","Here for the vibes 🎵"],Thando:["Johannesburg","Tech, Side Hustles","Building things 💻"],Lebo:["Cape Town","Students, Music","Coffee & good conversations ☕"],Kay:["Pretoria","Gaming, Football","GG 🎮"],Amahle:["Durban","Just Chatting, Music","Soft life enthusiast ✨"],Neo:["Johannesburg","Tech, Gaming","Always online somehow 😭"],Sbu:["Cape Town","Football, General","Up the Bucs ⚽"],Mia:["Pretoria","Students, Music","Just figuring it out 🌻"]}; let friends=JSON.parse(localStorage.getItem("awehFriends")||'["Zee"]'); let joinedRooms=JSON.parse(localStorage.getItem("awehRooms")||'["General","Just Chatting"]');
const samples=[["Zee","Sharp everyone 👋 how's your day going?"],["Thando","Anyone else avoiding work in here? 😭"],["Lebo","Aweh! This room is actually alive today 😂"],["Kay","What's everyone listening to right now?"]];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); let currentRoom=rooms[0][1];
let profile=JSON.parse(localStorage.getItem("awehProfile")||'{"name":"aweh_user","bio":"Just vibing ✨","status":"Online"}');
function save(){localStorage.setItem("awehProfile",JSON.stringify(profile))}
function toast(t){const e=$("#toast");e.textContent=t;e.style.display="block";setTimeout(()=>e.style.display="none",1800)}
function renderRooms(filter=""){ $("#rooms").innerHTML=rooms.filter(r=>(activeCat==="All"||r[3]===activeCat)&&r[1].toLowerCase().includes(filter.toLowerCase())).map(r=>`<button class="roomcard" data-room="${r[1]}"><span class="emoji">${r[0]}</span><b># ${r[1]}</b><small>🟢 ${r[2].toLocaleString()} online</small></button>`).join(""); $$(".roomcard").forEach(b=>b.onclick=()=>openRoom(b.dataset.room));}
function renderPeople(){ $("#people").innerHTML=people.map(n=>`<div class="person" data-person="${n}"><div class="pavatar">${n[0]}</div>${n}<span class="place">${userData[n][0]}</span></div>`).join(""); $$(".person").forEach(p=>p.onclick=()=>showUser(p.dataset.person)); renderRequests()}
function renderChats(){ $("#chatList").innerHTML=[["Zee","Did you see that? 😂","2m","2"],["Thando","Sharp, chat later","18m",""],["Lebo","Send me the link please","1h","1"],["Kay","Aweh!","3h",""]].map(x=>`<div class="chatrow" data-person="${x[0]}"><div class="pavatar">${x[0][0]}</div><div><b>${x[0]}</b><p>${x[1]}</p></div><time>${x[2]}</time>${x[3]?`<span class="unread">${x[3]}</span>`:""}</div>`).join(""); $$(".chatrow").forEach(r=>r.onclick=()=>openDM(r.dataset.person))}
function renderProfile(){ $("#profileName").textContent="@"+profile.name;$("#helloName").textContent="@"+profile.name;$("#profileBio").textContent=profile.bio;$("#profileStatus").textContent="● "+profile.status;$(".bigavatar").textContent=profile.name[0].toUpperCase();$(".avatar").textContent=profile.name[0].toUpperCase()}
function tab(id){ $$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$$("nav button").forEach(b=>b.classList.toggle("selected",b.dataset.tab===id));scrollTo(0,0)}
function openRoom(name){currentRoom=name;const r=rooms.find(x=>x[1]===name);$("#roomName").textContent="# "+name;$("#roomCount").textContent=r[2].toLocaleString()+" online";$("#messages").innerHTML=samples.map((m,i)=>`<div class="msg"><div class="mini">${m[0][0]}</div><div class="bubble"><b>@${m[0].toLowerCase()}</b><p>${m[1]}</p><small>${i+1} min ago</small></div></div>`).join("");tab("room")}
function modal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function renderRequests(){const box=$("#friendRequests");if(!box)return;const req=["Amahle","Neo"].filter(n=>!friends.includes(n));box.innerHTML=req.length?req.map(n=>`<div class="request"><div class="pavatar">${n[0]}</div><div class="who"><b>@${n.toLowerCase()}</b><small>${userData[n][0]}</small></div><button class="accept" data-accept="${n}">Add</button><button class="decline" data-decline="${n}">×</button></div>`).join(""):'<p class="muted">You’re all caught up ✨</p>';$("#requestCount").textContent=req.length?req.length+" waiting":"All caught up"}
function showUser(name){const u=userData[name]||["South Africa","General","Aweh 👋"];$("#viewProfile").innerHTML=`<div class="public-profile"><div class="bigavatar">${name[0]}</div><h2>@${name.toLowerCase()}</h2><span class="place">📍 ${u[0]} · 🟢 Online</span><p>${u[2]}</p><div class="profile-actions"><button class="primary" data-message="${name}">Message</button><button class="secondary ${friends.includes(name)?"joined":""}" data-friend="${name}">${friends.includes(name)?"✓ Friends":"+ Add friend"}</button></div><div class="roominfo"><h3>Rooms</h3><p>${u[1]}</p></div></div>`;tab("userProfile")}
function openDM(name){$("#dmName").textContent="@"+name.toLowerCase();$("#dmMessages").innerHTML=`<div class="msg"><div class="mini">${name[0]}</div><div class="bubble"><b>@${name.toLowerCase()}</b><p>Aweh 👋 nice to see you here!</p><small>5 min ago</small></div></div><div class="msg me"><div class="mini">${profile.name[0].toUpperCase()}</div><div class="bubble"><b>@${profile.name}</b><p>Sharp! 😄</p><small>4 min ago</small></div></div>`;tab("dm")}
$("#enterBtn").onclick=()=>{if(!localStorage.getItem("awehJoined")) modal(`<h2>Welcome to Aweh 🇿🇦</h2><p class="muted">Pick a username. You can change it later.</p><label>Username</label><input id="joinName" maxlength="18" placeholder="e.g. Noku92"><label>Status message</label><input id="joinBio" maxlength="60" placeholder="What's the vibe?"><button class="primary" id="joinNow">Let's go</button>`);else{$("#welcome").classList.add("hidden");$("#app").classList.remove("hidden");renderProfile()}};
document.addEventListener("click",e=>{if(e.target.id==="joinNow"){const n=$("#joinName").value.trim().replace(/[^a-zA-Z0-9_]/g,"");if(n.length<3)return toast("Username needs at least 3 characters");profile.name=n;profile.bio=$("#joinBio").value.trim()||"Just vibing ✨";save();localStorage.setItem("awehJoined","1");$("#modal").classList.add("hidden");$("#welcome").classList.add("hidden");$("#app").classList.remove("hidden");renderProfile();toast("Aweh, @"+n+"! 👋")}});
$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.add("hidden")};
$$("[data-tab]").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$("[data-go]").forEach(b=>b.onclick=()=>tab(b.dataset.go));
document.addEventListener("click",e=>{const a=e.target.dataset.accept,d=e.target.dataset.decline,f=e.target.dataset.friend,m=e.target.dataset.message;if(a){friends=[...new Set([...friends,a])];localStorage.setItem("awehFriends",JSON.stringify(friends));renderRequests();toast("@"+a.toLowerCase()+" added 🤝")}if(d){e.target.closest(".request").remove();toast("Request removed")}if(f){if(friends.includes(f))friends=friends.filter(x=>x!==f);else friends.push(f);localStorage.setItem("awehFriends",JSON.stringify(friends));showUser(f);toast(friends.includes(f)?"Friend added 🤝":"Friend removed")}if(m)openDM(m)});
if($("#roomMenu")) $("#roomMenu").onclick=()=>{const joined=joinedRooms.includes(currentRoom);modal(`<h2># ${currentRoom}</h2><div class="roominfo"><h3>About this room</h3><p>A place for the Aweh community to chat about ${currentRoom.toLowerCase()}, meet people and keep the conversation going.</p></div><div class="room-actions"><button id="joinRoom">${joined?"✓ Joined · Leave room":"+ Join room"}</button><button id="muteRoom">🔕 Mute notifications</button><button id="reportRoom">⚑ Report room</button></div>`)};
document.addEventListener("click",e=>{if(e.target.id==="joinRoom"){if(joinedRooms.includes(currentRoom))joinedRooms=joinedRooms.filter(x=>x!==currentRoom);else joinedRooms.push(currentRoom);localStorage.setItem("awehRooms",JSON.stringify(joinedRooms));$("#modal").classList.add("hidden");toast(joinedRooms.includes(currentRoom)?"Joined #"+currentRoom:"Left #"+currentRoom)}if(e.target.id==="muteRoom"){toast("Room muted 🔕");$("#modal").classList.add("hidden")}if(e.target.id==="reportRoom"){toast("Report flow preview ⚑");$("#modal").classList.add("hidden")}});
$("#roomsNav").onclick=()=>{tab("home");$("#rooms").scrollIntoView({behavior:"smooth"})};$("#search").oninput=e=>renderRooms(e.target.value);
$$(".chip").forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;$$(".chip").forEach(x=>x.classList.toggle("active",x===b));renderRooms($("#search").value)});
if($("#dmComposer")) $("#dmComposer").onsubmit=e=>{e.preventDefault();const i=$("#dmInput"),t=i.value.trim();if(!t)return;$("#dmMessages").insertAdjacentHTML("beforeend",`<div class="msg me"><div class="mini">${profile.name[0].toUpperCase()}</div><div class="bubble"><b>@${profile.name}</b><p></p><small>now</small></div></div>`);$("#dmMessages .msg:last-child p").textContent=t;i.value=""};
if($("#notifBtn")) $("#notifBtn").onclick=()=>modal(`<h2>Notifications 🔔</h2><div class="notice"><b>Zee sent you a message</b><small>2 minutes ago</small></div><div class="notice"><b>🔥 Just Chatting is trending</b><small>18 minutes ago</small></div><div class="notice"><b>Thando added you</b><small>1 hour ago</small></div>`);
$("#composer").onsubmit=e=>{e.preventDefault();const i=$("#messageInput"),t=i.value.trim();if(!t)return;$("#messages").insertAdjacentHTML("beforeend",`<div class="msg me"><div class="mini">${profile.name[0].toUpperCase()}</div><div class="bubble"><b>@${profile.name}</b><p></p><small>now</small></div></div>`);$("#messages .msg:last-child p").textContent=t;i.value="";scrollTo(0,document.body.scrollHeight)};
$("#statusBtn").onclick=()=>modal(`<h2>Set your status</h2>${["Online","Away","Busy","Invisible"].map(s=>`<button class="settings statusChoice" data-status="${s}">● ${s}</button>`).join("")}`);
document.addEventListener("click",e=>{if(e.target.classList.contains("statusChoice")){profile.status=e.target.dataset.status;save();$("#statusBtn").textContent="● "+profile.status;renderProfile();$("#modal").classList.add("hidden")}});
$("#editProfile").onclick=()=>modal(`<h2>Edit profile</h2><label>Username</label><input id="editName" maxlength="18" value="${profile.name}"><label>Status message</label><textarea id="editBio" maxlength="60">${profile.bio}</textarea><button id="saveProfile" class="primary">Save profile</button>`);
document.addEventListener("click",e=>{if(e.target.id==="saveProfile"){profile.name=$("#editName").value.trim()||profile.name;profile.bio=$("#editBio").value.trim();save();renderProfile();$("#modal").classList.add("hidden");toast("Profile updated")}});
$("#darkToggle").onclick=()=>toast("Aweh looks best after dark 🌙");let ds=localStorage.getItem("dataSaver")==="1";$("#dataToggle span").textContent=ds?"On":"Off";$("#dataToggle").onclick=()=>{ds=!ds;localStorage.setItem("dataSaver",ds?"1":"0");$("#dataToggle span").textContent=ds?"On":"Off";toast(ds?"Data saver on 📶":"Data saver off")};
if($("#locationBtn")) $("#locationBtn").onclick=()=>modal(`<h2>Choose your city 📍</h2><select id="citySelect"><option>Durban</option><option>Johannesburg</option><option>Cape Town</option><option>Pretoria</option><option>Gqeberha</option><option>Bloemfontein</option><option>Other</option></select><button class="primary" id="saveCity">Save city</button>`);
document.addEventListener("click",e=>{if(e.target.id==="saveCity"){localStorage.setItem("awehCity",$("#citySelect").value);$("#cityValue").textContent=$("#citySelect").value;$("#modal").classList.add("hidden");toast("City updated 📍")}});
if($("#cityValue")) $("#cityValue").textContent=localStorage.getItem("awehCity")||"Not set";
$("#aboutBtn").onclick=()=>modal(`<h2>aweh<span style="color:#b7f34b">.</span></h2><p><b>South Africa is online. 🇿🇦</b></p><p class="muted">A lightweight community chat concept built for conversations, rooms and finding your people.</p><p class="muted">Phase 1 is a front-end prototype. Messages are currently stored only in this browser session and are not sent to other users.</p>`);
renderRooms();renderPeople();renderChats();renderProfile();