const rooms=[["😂","Just Chatting",1284,"Social"],["🎵","Music",976,"Lifestyle"],["🎮","Gaming",603,"Lifestyle"],["⚽","Football",557,"Lifestyle"],["💼","Jobs & Careers",842,"Career"],["💻","Tech",391,"Career"],["💰","Side Hustles",419,"Career"],["🎓","Students",734,"Career"],["🌍","General",1120,"Social"],["🌊","Durban",688,"Places"],["🏙️","Johannesburg",1056,"Places"],["⛰️","Cape Town",901,"Places"],["🌳","Pretoria",512,"Places"],["🌅","Gqeberha",247,"Places"],["🌻","Bloemfontein",198,"Places"]]; let activeCat="All";
const people=["Zee","Thando","Lebo","Kay","Amahle","Neo","Sbu","Mia"];
const samples=[["Zee","Sharp everyone 👋 how's your day going?"],["Thando","Anyone else avoiding work in here? 😭"],["Lebo","Aweh! This room is actually alive today 😂"],["Kay","What's everyone listening to right now?"]];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); let currentRoom=rooms[0][1];
let profile=JSON.parse(localStorage.getItem("awehProfile")||'{"name":"aweh_user","bio":"Just vibing ✨","status":"Online"}');
function save(){localStorage.setItem("awehProfile",JSON.stringify(profile))}
function toast(t){const e=$("#toast");e.textContent=t;e.style.display="block";setTimeout(()=>e.style.display="none",1800)}
function renderRooms(filter=""){ $("#rooms").innerHTML=rooms.filter(r=>(activeCat==="All"||r[3]===activeCat)&&r[1].toLowerCase().includes(filter.toLowerCase())).map(r=>`<button class="roomcard" data-room="${r[1]}"><span class="emoji">${r[0]}</span><b># ${r[1]}</b><small>🟢 ${r[2].toLocaleString()} online</small></button>`).join(""); $$(".roomcard").forEach(b=>b.onclick=()=>openRoom(b.dataset.room));}
function renderPeople(){ $("#people").innerHTML=people.map((n,i)=>`<div class="person" data-person="${n}"><div class="pavatar">${n[0]}</div>${n}<span class="place">${["Durban","Joburg","Cape Town","Pretoria"][i%4]}</span></div>`).join(""); $(".person").forEach(p=>p.onclick=()=>openDM(p.dataset.person))}
function renderChats(){ $("#chatList").innerHTML=[["Zee","Did you see that? 😂","2m","2"],["Thando","Sharp, chat later","18m",""],["Lebo","Send me the link please","1h","1"],["Kay","Aweh!","3h",""]].map(x=>`<div class="chatrow" data-person="${x[0]}"><div class="pavatar">${x[0][0]}</div><div><b>${x[0]}</b><p>${x[1]}</p></div><time>${x[2]}</time>${x[3]?`<span class="unread">${x[3]}</span>`:""}</div>`).join(""); $(".chatrow").forEach(r=>r.onclick=()=>openDM(r.dataset.person))}
function renderProfile(){ $("#profileName").textContent="@"+profile.name;$("#helloName").textContent="@"+profile.name;$("#profileBio").textContent=profile.bio;$("#profileStatus").textContent="● "+profile.status;$(".bigavatar").textContent=profile.name[0].toUpperCase();$(".avatar").textContent=profile.name[0].toUpperCase()}
function tab(id){ $$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$$("nav button").forEach(b=>b.classList.toggle("selected",b.dataset.tab===id));scrollTo(0,0)}
function openRoom(name){currentRoom=name;const r=rooms.find(x=>x[1]===name);$("#roomName").textContent="# "+name;$("#roomCount").textContent=r[2].toLocaleString()+" online";$("#messages").innerHTML=samples.map((m,i)=>`<div class="msg"><div class="mini">${m[0][0]}</div><div class="bubble"><b>@${m[0].toLowerCase()}</b><p>${m[1]}</p><small>${i+1} min ago</small></div></div>`).join("");tab("room")}
function modal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function openDM(name){$("#dmName").textContent="@"+name.toLowerCase();$("#dmMessages").innerHTML=`<div class="msg"><div class="mini">${name[0]}</div><div class="bubble"><b>@${name.toLowerCase()}</b><p>Aweh 👋 nice to see you here!</p><small>5 min ago</small></div></div><div class="msg me"><div class="mini">${profile.name[0].toUpperCase()}</div><div class="bubble"><b>@${profile.name}</b><p>Sharp! 😄</p><small>4 min ago</small></div></div>`;tab("dm")}
$("#enterBtn").onclick=()=>{if(!localStorage.getItem("awehJoined")) modal(`<h2>Welcome to Aweh 🇿🇦</h2><p class="muted">Pick a username. You can change it later.</p><label>Username</label><input id="joinName" maxlength="18" placeholder="e.g. Noku92"><label>Status message</label><input id="joinBio" maxlength="60" placeholder="What's the vibe?"><button class="primary" id="joinNow">Let's go</button>`);else{$("#welcome").classList.add("hidden");$("#app").classList.remove("hidden");renderProfile()}};
document.addEventListener("click",e=>{if(e.target.id==="joinNow"){const n=$("#joinName").value.trim().replace(/[^a-zA-Z0-9_]/g,"");if(n.length<3)return toast("Username needs at least 3 characters");profile.name=n;profile.bio=$("#joinBio").value.trim()||"Just vibing ✨";save();localStorage.setItem("awehJoined","1");$("#modal").classList.add("hidden");$("#welcome").classList.add("hidden");$("#app").classList.remove("hidden");renderProfile();toast("Aweh, @"+n+"! 👋")}});
$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.add("hidden")};
$$("[data-tab]").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$("[data-go]").forEach(b=>b.onclick=()=>tab(b.dataset.go));
$("#roomsNav").onclick=()=>{tab("home");$("#rooms").scrollIntoView({behavior:"smooth"})};$("#search").oninput=e=>renderRooms(e.target.value);
$(".chip").forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;$(".chip").forEach(x=>x.classList.toggle("active",x===b));renderRooms($("#search").value)});
$("#dmComposer").onsubmit=e=>{e.preventDefault();const i=$("#dmInput"),t=i.value.trim();if(!t)return;$("#dmMessages").insertAdjacentHTML("beforeend",`<div class="msg me"><div class="mini">${profile.name[0].toUpperCase()}</div><div class="bubble"><b>@${profile.name}</b><p></p><small>now</small></div></div>`);$("#dmMessages .msg:last-child p").textContent=t;i.value=""};
$("#notifBtn").onclick=()=>modal(`<h2>Notifications 🔔</h2><div class="notice"><b>Zee sent you a message</b><small>2 minutes ago</small></div><div class="notice"><b>🔥 Just Chatting is trending</b><small>18 minutes ago</small></div><div class="notice"><b>Thando added you</b><small>1 hour ago</small></div>`);
$("#composer").onsubmit=e=>{e.preventDefault();const i=$("#messageInput"),t=i.value.trim();if(!t)return;$("#messages").insertAdjacentHTML("beforeend",`<div class="msg me"><div class="mini">${profile.name[0].toUpperCase()}</div><div class="bubble"><b>@${profile.name}</b><p></p><small>now</small></div></div>`);$("#messages .msg:last-child p").textContent=t;i.value="";scrollTo(0,document.body.scrollHeight)};
$("#statusBtn").onclick=()=>modal(`<h2>Set your status</h2>${["Online","Away","Busy","Invisible"].map(s=>`<button class="settings statusChoice" data-status="${s}">● ${s}</button>`).join("")}`);
document.addEventListener("click",e=>{if(e.target.classList.contains("statusChoice")){profile.status=e.target.dataset.status;save();$("#statusBtn").textContent="● "+profile.status;renderProfile();$("#modal").classList.add("hidden")}});
$("#editProfile").onclick=()=>modal(`<h2>Edit profile</h2><label>Username</label><input id="editName" maxlength="18" value="${profile.name}"><label>Status message</label><textarea id="editBio" maxlength="60">${profile.bio}</textarea><button id="saveProfile" class="primary">Save profile</button>`);
document.addEventListener("click",e=>{if(e.target.id==="saveProfile"){profile.name=$("#editName").value.trim()||profile.name;profile.bio=$("#editBio").value.trim();save();renderProfile();$("#modal").classList.add("hidden");toast("Profile updated")}});
$("#darkToggle").onclick=()=>toast("Aweh looks best after dark 🌙");let ds=localStorage.getItem("dataSaver")==="1";$("#dataToggle span").textContent=ds?"On":"Off";$("#dataToggle").onclick=()=>{ds=!ds;localStorage.setItem("dataSaver",ds?"1":"0");$("#dataToggle span").textContent=ds?"On":"Off";toast(ds?"Data saver on 📶":"Data saver off")};
$("#locationBtn").onclick=()=>modal(`<h2>Choose your city 📍</h2><select id="citySelect"><option>Durban</option><option>Johannesburg</option><option>Cape Town</option><option>Pretoria</option><option>Gqeberha</option><option>Bloemfontein</option><option>Other</option></select><button class="primary" id="saveCity">Save city</button>`);
document.addEventListener("click",e=>{if(e.target.id==="saveCity"){localStorage.setItem("awehCity",$("#citySelect").value);$("#cityValue").textContent=$("#citySelect").value;$("#modal").classList.add("hidden");toast("City updated 📍")}});
$("#cityValue").textContent=localStorage.getItem("awehCity")||"Not set";
$("#aboutBtn").onclick=()=>modal(`<h2>aweh<span style="color:#b7f34b">.</span></h2><p><b>South Africa is online. 🇿🇦</b></p><p class="muted">A lightweight community chat concept built for conversations, rooms and finding your people.</p><p class="muted">Phase 1 is a front-end prototype. Messages are currently stored only in this browser session and are not sent to other users.</p>`);
renderRooms();renderPeople();renderChats();renderProfile();